### ISSUE TITLE
Comment, Agree API 수정사항 반영

### ISSUE THREAD

**Issue by kimjngyun** [GIST-Petition-Site-Project/GIST-petition-web-ts#169]
## 목적

Comment, Agree API 수정사항 반영을 진행합니다.

백엔드에서 comminet-controller 가 사라지며 댓글 기능이 
POST: /v1/petitions/{petitionsId}/agreemnets 로 
```
{
  "description": "string"
}
```
와 함께 보내는 것으로 변경되었습니다. 

따라서 현재 동의하기 버튼과 댓글 등록버튼을 통합하는 작업을 진행해야합니다. 

- [ ] 동의하기 버튼 제거
- [ ] 수정 API 반영
- [ ] 수정된 API 에 맞는 댓글(+동의) UI 설계 및 퍼블리싱

**Comment by leejimin-gist** [comment]
제가 해봐도 될까요?

**Comment by kimjngyun** [comment]
물론이죠!
