### ISSUE TITLE
Mobile에서 footer 양쪽에 padding값 넣는걸  제안합니다.

### ISSUE THREAD

**Issue by choi2021** [GIST-Petition-Site-Project/GIST-petition-web-ts#192]
## 목적

mobile에서 footer가 너무 딱맞게 나옵니다. padding을 양쪽에 넣으면 좋겠어서 제안합니다.

## 작업 목록

- [ ] A
- [ ] B

**Comment by gpgun0** [comment]
바로 적용하겠습니다.
