### ISSUE TITLE
모바일 NavBar Collapse 적용

### ISSUE THREAD

**Issue by leejimin-gist** [GIST-Petition-Site-Project/GIST-petition-web-ts#204]
## 목적
모바일 NavBar Collapse 적용합니다
## 작업 목록

- [ ] 모바일 NavBar Collapse 적용

**Comment by gpgun0** [comment]
요거는 chakra 안불러오고 지금 상태에서 transition만 줘도 가능할 거 같아요

일단 제가 시도해보고 안되면 다시 알려드릴게요

**Comment by leejimin-gist** [comment]
> 요거는 chakra 안불러오고 지금 상태에서 transition만 줘도 가능할 거 같아요
> 
> 일단 제가 시도해보고 안되면 다시 알려드릴게요

제가 해놨어요! 이따가 home이랑 같이 pr날리려고 이슈올려놨습니다.

**Comment by gpgun0** [comment]
> 

좋습니다!
