### ISSUE TITLE
비밀번호 변경 후 다시 비밀번호 변경 페이지를 들어가면 모든 input 창이 보입니다.

### ISSUE THREAD

**Issue by gpgun0** [GIST-Petition-Site-Project/GIST-petition-web-ts#236]
## 상세 설명

비밀번호 변경 후 다시 비밀번호 변경 페이지를 들어가면 모든 input 창이 보입니다.

## 대처 방안

비밀번호 변경 페이지 링크는 a태그로 확정짓겠습니다.

**Comment by choi2021** [comment]
회원가입페이지와 함께 제가 수정하겠습니다.
