### ISSUE TITLE
네비게이션 바에서 내 정보 메뉴 위치 수정 필요

### ISSUE THREAD

**Issue by leejimin-gist** [GIST-Petition-Site-Project/GIST-petition-web-ts#263]
## 목적
내정보 메뉴가 다른 메뉴보다 내려와있습니다. 수정 필요합니다.

## 작업 목록
![캡처](https://user-images.githubusercontent.com/77228503/155871368-5323279b-39be-4a54-b63f-2232a8c81bbf.PNG)

- [ ] A

- [ ] B

**Comment by gpgun0** [comment]
반영했습니다 👍
